package com.example.ui.screens

import android.util.Log
import android.widget.Toast
import androidx.compose.foundation.layout.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.credentials.CredentialManager
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialException
import com.example.R
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import java.security.MessageDigest
import java.util.UUID

@Composable
fun LoginScreen(onLoginSuccess: () -> Unit) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    var isLoading by remember { mutableStateOf(false) }

    // Check if already logged in
    LaunchedEffect(Unit) {
        if (FirebaseAuth.getInstance().currentUser != null) {
            onLoginSuccess()
        }
    }

    Box(
        modifier = Modifier.fillMaxSize(),
        contentAlignment = Alignment.Center
    ) {
        Column(
            horizontalAlignment = Alignment.CenterHorizontally,
            modifier = Modifier.padding(32.dp)
        ) {
            Text(
                "Welcome to Sync Control",
                fontSize = 24.sp,
                fontWeight = FontWeight.Bold,
                color = MaterialTheme.colorScheme.primary
            )
            Spacer(modifier = Modifier.height(16.dp))
            Text(
                "Please sign in with your Google Account to continue. This ensures your devices are securely connected.",
                fontSize = 16.sp,
                color = MaterialTheme.colorScheme.onSurface.copy(alpha = 0.7f),
                textAlign = androidx.compose.ui.text.style.TextAlign.Center
            )
            Spacer(modifier = Modifier.height(32.dp))

            if (isLoading) {
                CircularProgressIndicator()
            } else {
                Button(
                    onClick = {
                        isLoading = true
                        coroutineScope.launch {
                            try {
                                val auth = FirebaseAuth.getInstance()
                                val credentialManager = CredentialManager.create(context)
                                
                                // We need a Web Client ID from the strings.xml (usually generated by Firebase)
                                // In Android, the google-services.json has a client_id with client_type 3 (Web).
                                // As a fallback, we'll try to find it in strings.
                                                                val resId = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
                                if (resId == 0) {
                                    Toast.makeText(context, "Setup Error: default_web_client_id not found. Please add a valid google-services.json", Toast.LENGTH_LONG).show()
                                    isLoading = false
                                    return@launch
                                }
                                val webClientId = context.getString(resId)
                                
                                val rawNonce = UUID.randomUUID().toString()
                                val bytes = rawNonce.toByteArray()
                                val md = MessageDigest.getInstance("SHA-256")
                                val digest = md.digest(bytes)
                                val hashedNonce = digest.joinToString("") { "%02x".format(it) }

                                val googleIdOption: GetGoogleIdOption = GetGoogleIdOption.Builder()
                                    .setFilterByAuthorizedAccounts(false)
                                    .setServerClientId(webClientId)
                                    .setNonce(hashedNonce)
                                    .build()

                                val request: GetCredentialRequest = GetCredentialRequest.Builder()
                                    .addCredentialOption(googleIdOption)
                                    .build()

                                val result = credentialManager.getCredential(
                                    request = request,
                                    context = context,
                                )

                                val credential = result.credential
                                if (credential is GoogleIdTokenCredential) {
                                    val idToken = credential.idToken
                                    val firebaseCredential = GoogleAuthProvider.getCredential(idToken, null)
                                    auth.signInWithCredential(firebaseCredential).await()
                                    onLoginSuccess()
                                } else {
                                    Log.e("Auth", "Unexpected type of credential")
                                    Toast.makeText(context, "Login failed: Unexpected credential type", Toast.LENGTH_SHORT).show()
                                }
                            } catch (e: Exception) {
                                Log.e("Auth", "Google sign in failed", e)
                                Toast.makeText(context, "Google Sign In Failed. Is google-services.json correctly configured with SHA-1?", Toast.LENGTH_LONG).show()
                            } finally {
                                isLoading = false
                            }
                        }
                    },
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(50.dp)
                ) {
                    Text("Continue with Google", fontSize = 16.sp)
                }
            }
        }
    }
}
